# This is a template part and needs to be copied and pasted into your main Magic container
# docker-compose.yml file.
# By adding the service below to your main Magic docker-compose file, you will serve your crudified
# frontend as a part of the main docker-compose.yml file.

  # Your app's main container
  sakila:
    container_name: sakila
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:

      # REPLACE THESE NEXT 3 PARTS WITH YOUR OWN DOMAIN/EMAIL
      - VIRTUAL_HOST=sakila.servergardens.com
      - LETSENCRYPT_HOST=sakila.servergardens.com
      - LETSENCRYPT_EMAIL=thomas@servergardens.com

    # This pulls in our ".env" file, which will include the entirety of our main Magic docker-compose.yml file.
    env_file:
      - .env

