version: "2"

services:

  # This is the internet facing reverse proxy that routes
  # requests to your specific part, backend/frontend/etc.
  # This is the only thing that's actually exposed to the internet.
  nginx-proxy-crud:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy-crud
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /usr/share/nginx/html
    networks:
      - proxy
    restart: always

  # This is the container that is responsible for retrieving
  # and renewing SSL certificates from LetsEncrypt
  letsencrypt-crud:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    volumes_from:
      - nginx-proxy-crud
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    restart: always

  # Your app's main container
  sakila:
    container_name: sakila
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:

      # REPLACE THESE NEXT 3 PARTS WITH YOUR OWN DOMAIN/EMAIL
      - VIRTUAL_HOST=sakila.servergardens.com
      - LETSENCRYPT_HOST=sakila.servergardens.com
      - LETSENCRYPT_EMAIL=thomas@servergardens.com

    networks:
      - proxy

networks:
  proxy:
    external:
      name: nginx-proxy

volumes:
  conf:
  vhost:
  dhparam:
  certs:
