/*
 * Automatically generated by Magic
 */

// Angular specific components
import { throwError } from 'rxjs';
import { Component, OnInit, ViewChild } from '@angular/core';
import { MatSnackBar } from '@angular/material/snack-bar';
import { GridComponent } from '@app/base/grid.component';
import { MatPaginator } from '@angular/material/paginator';
import { MatDialog } from '@angular/material/dialog';
import { FormControl } from '@angular/forms';
import {
  trigger,
  state,
  style,
  transition,
  animate
} from '@angular/animations';

// Application specific components
import { EditSakila_filmComponent } from './modals/edit.sakila_film.component';
import { HttpService } from 'src/app/services/http-service';
import { AuthService } from 'src/app/services/auth-service';

/**
 * "Datagrid" component for displaying instance of Film
 * entities from your HTTP REST backend.
 */
@Component({
  selector: 'app-sakila_film',
  templateUrl: './sakila_film.component.html',
  styleUrls: ['./sakila_film.component.scss'],
  animations: [
    trigger('detailExpand', [
      state('collapsed', style({height: '0px', opacity: '0'})),
      state('expanded', style({height: '*', opacity: '1'})),
      transition('expanded <=> collapsed', animate('0.75s cubic-bezier(0.4, 0.0, 0.2, 1)')),
    ])
  ]
})
export class Sakila_filmComponent extends GridComponent implements OnInit {

  /**
   * Which columns we should display. Reorder to prioritize columns differently.
   * Notice! 'delete-instance' should always come last.
   */
  public displayedColumns: string[] = [
    'language_id.name',
    'original_language_id.name',
    'title',
    'description',
    'release_year',
    'rating',
    'special_features',
    'last_update',
    'rental_duration',
    'rental_rate',
    'length',
    'replacement_cost',
    'delete-instance'
  ];

  /**
   * What element is currently expanded.
   */
  public expandedElement: any | null;


  // Need to view paginator as a child to update page index of it.
  @ViewChild(MatPaginator, {static: true}) paginator: MatPaginator;

  // Form control declarations to bind up with reactive form elements.
  public language_id_name: FormControl;
  public original_language_id_name: FormControl;
  public title: FormControl;
  public description: FormControl;
  public release_year: FormControl;
  public rating: FormControl;
  public special_features: FormControl;
  public last_update: FormControl;
  public film_id: FormControl;
  public language_id: FormControl;
  public original_language_id: FormControl;
  public rental_duration: FormControl;
  public rental_rate: FormControl;
  public length: FormControl;
  public replacement_cost: FormControl;


  /**
   * Creates an instance of your CRUD component.
   * 
   * @param httpService Needed to be able to invoke backend during CRUD operations
   * @param authService Needed to check if user has access to invoking CRUD operation
   * @param snackBar Needed to display errror and feedback
   * @param dialog Needed to show modal dialog as user edits or creates new entities
   */
   constructor(
    public httpService: HttpService,
    public authService: AuthService,
    protected snackBar: MatSnackBar,
    protected dialog: MatDialog) {
      super(authService, snackBar, dialog);
  }

  /**
   * Overridde abstract method necessary to return the URL endpoint
   * for CRUD methods to base class.
   */
  public url() {
    return 'magic/modules/sakila/film';
  }

  /**
   * Overridden abstract method from base class, that returns the Observable
   * necessary to actually retrieve items from backend.
   */
  protected read(filter: any) {
    return this.httpService.sakila_film.read(filter);
  }

  /**
   * Overridden abstract method from base class, that returns the Observable
   * necessary to actually retrieve count of items from backend.
   */
  protected count(filter: any) {
    return this.httpService.sakila_film.count(filter);
  }

  /**
   * Overridden abstract method from base class, that returns the Observable
   * necessary to actually delete items in backend.
   */
  protected delete(ids: any) {
    return this.httpService.sakila_film.delete(ids);
  }

  /**
   * Implementation of abstract base class method, to reset paginator
   * of component.
   */
  protected resetPaginator() {
    this.paginator.pageIndex = 0;
    this.filter.offset = 0;
  }

  /**
   * OnInit implementation. Retrieves initial data (unfiltered),
   * and instantiates our FormControls.
   */
  public ngOnInit() {

    // Retrieves data from our backend, unfiltered, and binds our mat-table accordingly.
    this.getData();

    /*
     * Creating our filtering FormControl instances, which gives us "live filtering"
     * on our columns.
     */
    this.language_id_name = this.createFormControl('language_id.name.like');
    this.original_language_id_name = this.createFormControl('original_language_id.name.like');
    this.title = this.createFormControl('film.title.like');
    this.description = this.createFormControl('film.description.like');
    this.release_year = this.createFormControl('film.release_year.like');
    this.rating = this.createFormControl('film.rating.like');
    this.special_features = this.createFormControl('film.special_features.like');
    this.last_update = this.createFormControl('film.last_update.eq');
    this.film_id = this.createFormControl('film.film_id.eq');
    this.language_id = this.createFormControl('film.language_id.eq');
    this.original_language_id = this.createFormControl('film.original_language_id.eq');
    this.rental_duration = this.createFormControl('film.rental_duration.eq');
    this.rental_rate = this.createFormControl('film.rental_rate.eq');
    this.length = this.createFormControl('film.length.eq');
    this.replacement_cost = this.createFormControl('film.replacement_cost.eq');
  }

  /**
   * Invoked when user wants to edit an entity
   * 
   * This will show a modal dialog, allowing the user to edit his record.
   */
  public editEntity(entity: any) {

    const dialogRef = this.dialog.open(EditSakila_filmComponent, {
      data: this.getEditData(entity)
    });
    dialogRef.afterClosed().subscribe(res => {
      if (res) {
        this.setEditData(res, entity);
      }
    });
  }

  /**
   * Invoked when user wants to create a new entity
   * 
   * This will show a modal dialog, allowing the user to supply
   * the initial data for the entity.
   */
  public createEntity() {

    const dialogRef = this.dialog.open(EditSakila_filmComponent, {
      data: {
        isEdit: false,
        entity: {},
      }});
    dialogRef.afterClosed().subscribe((res: any) => {
      if (res) {
        this.itemCreated(res);
      }
    });
  }
}
