/*
 * Automatically generated by Magic
 */

import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';
import { TranslateModule } from '@ngx-translate/core';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { MaterialModule } from './material.module';
import { NgxImageCompressService } from 'ngx-image-compress';

import { CoreModule } from '@core';
import { SharedModule } from '@shared';
import { AuthModule } from '@app/auth';
import { HomeModule } from './home/home.module';
import { ShellModule } from './shell/shell.module';
import { AppComponent } from './app.component';
import { MagicSelectorComponent } from './helpers/magic-selector/magic-selector.component';
import { MagicAutocompleteComponent } from './helpers/magic-autocomplete/magic-autocomplete.component';
import { MagicFilterComponent } from './helpers/magic-filter/magic-filter.component';
import { MagicImageComponent } from './helpers/magic-image/magic-image.component';
import { MagicImageViewComponent } from './helpers/magic-image-view/magic-image-view.component';
import { MagicFileViewComponent } from './helpers/magic-file-view/magic-file-view.component';
import { MagicFileComponent } from './helpers/magic-file/magic-file.component';
import { AppRoutingModule } from './app-routing.module';
import { environment } from '@env/environment';
import { JwtModule } from '@auth0/angular-jwt';
import { OwlDateTimeModule, OwlNativeDateTimeModule } from '@danielmoncada/angular-datetime-picker';
import { FormatDatePipe } from './pipes/format-date-pipe';
import { DateSincePipe } from './pipes/date-since.pipe';
import { ConfirmDialogComponent } from './confirm-deletion-dialog/confirm-dialog.component';

// Generated CRUD components here.
import { Sakila_actorComponent } from './components/sakila/actor/sakila_actor.component';
import { EditSakila_actorComponent } from './components/sakila/actor/modals/edit.sakila_actor.component';
import { Sakila_addressComponent } from './components/sakila/address/sakila_address.component';
import { EditSakila_addressComponent } from './components/sakila/address/modals/edit.sakila_address.component';
import { Sakila_categoryComponent } from './components/sakila/category/sakila_category.component';
import { EditSakila_categoryComponent } from './components/sakila/category/modals/edit.sakila_category.component';
import { Sakila_cityComponent } from './components/sakila/city/sakila_city.component';
import { EditSakila_cityComponent } from './components/sakila/city/modals/edit.sakila_city.component';
import { Sakila_countryComponent } from './components/sakila/country/sakila_country.component';
import { EditSakila_countryComponent } from './components/sakila/country/modals/edit.sakila_country.component';
import { Sakila_customerComponent } from './components/sakila/customer/sakila_customer.component';
import { EditSakila_customerComponent } from './components/sakila/customer/modals/edit.sakila_customer.component';
import { Sakila_film_actorComponent } from './components/sakila/film_actor/sakila_film_actor.component';
import { EditSakila_film_actorComponent } from './components/sakila/film_actor/modals/edit.sakila_film_actor.component';
import { Sakila_film_categoryComponent } from './components/sakila/film_category/sakila_film_category.component';
import { EditSakila_film_categoryComponent } from './components/sakila/film_category/modals/edit.sakila_film_category.component';
import { Sakila_filmComponent } from './components/sakila/film/sakila_film.component';
import { EditSakila_filmComponent } from './components/sakila/film/modals/edit.sakila_film.component';
import { Sakila_inventoryComponent } from './components/sakila/inventory/sakila_inventory.component';
import { EditSakila_inventoryComponent } from './components/sakila/inventory/modals/edit.sakila_inventory.component';
import { Sakila_languageComponent } from './components/sakila/language/sakila_language.component';
import { EditSakila_languageComponent } from './components/sakila/language/modals/edit.sakila_language.component';
import { Sakila_paymentComponent } from './components/sakila/payment/sakila_payment.component';
import { EditSakila_paymentComponent } from './components/sakila/payment/modals/edit.sakila_payment.component';
import { Sakila_rentalComponent } from './components/sakila/rental/sakila_rental.component';
import { EditSakila_rentalComponent } from './components/sakila/rental/modals/edit.sakila_rental.component';
import { Sakila_staffComponent } from './components/sakila/staff/sakila_staff.component';
import { EditSakila_staffComponent } from './components/sakila/staff/modals/edit.sakila_staff.component';
import { Sakila_storeComponent } from './components/sakila/store/sakila_store.component';
import { EditSakila_storeComponent } from './components/sakila/store/modals/edit.sakila_store.component';


@NgModule({
  imports: [
    OwlDateTimeModule,
    OwlNativeDateTimeModule,
    BrowserModule,
    FormsModule,
    ReactiveFormsModule,
    HttpClientModule,
    TranslateModule.forRoot(),
    BrowserAnimationsModule,
    MaterialModule,
    CoreModule,
    SharedModule,
    ShellModule,
    HomeModule,
    AuthModule,
    JwtModule.forRoot({
      config: {
        tokenGetter: () => {
          const persisted = sessionStorage.getItem('credentials') || localStorage.getItem('credentials');
          if (persisted) {
            return JSON.parse(persisted).token;
          }
          return null;
        },
        allowedDomains: [environment.apiDomain],
      },
    }),
    AppRoutingModule, // must be imported as the last module as it contains the fallback route
  ],
  declarations: [
    AppComponent,
    MagicSelectorComponent,
    MagicAutocompleteComponent,
    MagicFilterComponent,
    MagicImageComponent,
    MagicImageViewComponent,
    MagicFileViewComponent,
    MagicFileComponent,
    FormatDatePipe,
    DateSincePipe,
    ConfirmDialogComponent,

// Generated CRUD components here.
    Sakila_actorComponent,
    EditSakila_actorComponent,
    Sakila_addressComponent,
    EditSakila_addressComponent,
    Sakila_categoryComponent,
    EditSakila_categoryComponent,
    Sakila_cityComponent,
    EditSakila_cityComponent,
    Sakila_countryComponent,
    EditSakila_countryComponent,
    Sakila_customerComponent,
    EditSakila_customerComponent,
    Sakila_film_actorComponent,
    EditSakila_film_actorComponent,
    Sakila_film_categoryComponent,
    EditSakila_film_categoryComponent,
    Sakila_filmComponent,
    EditSakila_filmComponent,
    Sakila_inventoryComponent,
    EditSakila_inventoryComponent,
    Sakila_languageComponent,
    EditSakila_languageComponent,
    Sakila_paymentComponent,
    EditSakila_paymentComponent,
    Sakila_rentalComponent,
    EditSakila_rentalComponent,
    Sakila_staffComponent,
    EditSakila_staffComponent,
    Sakila_storeComponent,
    EditSakila_storeComponent,
  ],

  providers: [NgxImageCompressService],
  bootstrap: [AppComponent],
})
export class AppModule {}
