/*
 * Automatically generated by Magic
 */

import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { marker } from '@biesbjerg/ngx-translate-extract-marker';

import { HomeComponent } from './home.component';
import { Shell } from '@app/shell/shell.service';

// Then importing all CRUD components.
import { ActorComponent } from '../components/actor/actor.component';
import { AddressComponent } from '../components/address/address.component';
import { CategoryComponent } from '../components/category/category.component';
import { CityComponent } from '../components/city/city.component';
import { CountryComponent } from '../components/country/country.component';
import { CustomerComponent } from '../components/customer/customer.component';
import { Film_actorComponent } from '../components/film_actor/film_actor.component';
import { Film_categoryComponent } from '../components/film_category/film_category.component';
import { FilmComponent } from '../components/film/film.component';
import { InventoryComponent } from '../components/inventory/inventory.component';
import { LanguageComponent } from '../components/language/language.component';
import { PaymentComponent } from '../components/payment/payment.component';
import { RentalComponent } from '../components/rental/rental.component';
import { StaffComponent } from '../components/staff/staff.component';
import { StoreComponent } from '../components/store/store.component';


const routes: Routes = [
  Shell.childRoutes([
    { path: '', component: HomeComponent, data: { title: marker('Home') } },

    // Then routes for all CRUD components.
    { path: 'crud/actor', component: ActorComponent, data: { title: marker('actor') } },
    { path: 'crud/address', component: AddressComponent, data: { title: marker('address') } },
    { path: 'crud/category', component: CategoryComponent, data: { title: marker('category') } },
    { path: 'crud/city', component: CityComponent, data: { title: marker('city') } },
    { path: 'crud/country', component: CountryComponent, data: { title: marker('country') } },
    { path: 'crud/customer', component: CustomerComponent, data: { title: marker('customer') } },
    { path: 'crud/film_actor', component: Film_actorComponent, data: { title: marker('film_actor') } },
    { path: 'crud/film_category', component: Film_categoryComponent, data: { title: marker('film_category') } },
    { path: 'crud/film', component: FilmComponent, data: { title: marker('film') } },
    { path: 'crud/inventory', component: InventoryComponent, data: { title: marker('inventory') } },
    { path: 'crud/language', component: LanguageComponent, data: { title: marker('language') } },
    { path: 'crud/payment', component: PaymentComponent, data: { title: marker('payment') } },
    { path: 'crud/rental', component: RentalComponent, data: { title: marker('rental') } },
    { path: 'crud/staff', component: StaffComponent, data: { title: marker('staff') } },
    { path: 'crud/store', component: StoreComponent, data: { title: marker('store') } },

  ]),
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
  providers: [],
})
export class HomeRoutingModule {}
