# DEV CD pipeline, deploys to UpCloud droplet

name: Deployment-DEV

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: Checking out code
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Building the code
        run: |
          npm ci
          npm run build

      - name: Copy files to UpCloud server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEPLOYMENT_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT }}
          source: './sakila/'
          target: '/'
